def options(opt):
    pass


def configure(cnf):
    pass


def build(bld):
    out_dir = bld.path.make_node("../../dungeon")

    bld(
        features="plim",
        source="explored/index.plim",
        target=out_dir.make_node("explored.html"),
    )

    bld(
        features="elm",
        source="explored/Main.elm",
        target="explored.js",
    )
    bld(
        features="jsmin",
        source="explored.js",
        target=out_dir.make_node("explored.min.js"),
    )

    bld(
        features="sass",
        source="explored/style.sass",
        target=out_dir.make_node("explored.min.css"),
        options=bld.env.SASS_OPTIONS,
    )
