def options(opt):
    opt.recurse("dungeon  hexeditor")


def configure(cnf):
    cnf.load("elm  jsminc  lsc  plimc  sassc", tooldir="waftools")

    cnf.env.append_value("ELM_FLAGS", ["--yes", "--warn"])
    cnf.env.SASS_OPTIONS = {"output_style": "compressed"}

    cnf.recurse("dungeon  hexeditor")


def build(bld):
    bld.recurse("dungeon  hexeditor")
